/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Item as PrismaItem,
  Rental as PrismaRental,
  Review as PrismaReview,
  Location as PrismaLocation,
  ItemType as PrismaItemType,
} from "@prisma/client";

export class ItemServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ItemCountArgs, "select">): Promise<number> {
    return this.prisma.item.count(args);
  }

  async items(args: Prisma.ItemFindManyArgs): Promise<PrismaItem[]> {
    return this.prisma.item.findMany(args);
  }
  async item(args: Prisma.ItemFindUniqueArgs): Promise<PrismaItem | null> {
    return this.prisma.item.findUnique(args);
  }
  async createItem(args: Prisma.ItemCreateArgs): Promise<PrismaItem> {
    return this.prisma.item.create(args);
  }
  async updateItem(args: Prisma.ItemUpdateArgs): Promise<PrismaItem> {
    return this.prisma.item.update(args);
  }
  async deleteItem(args: Prisma.ItemDeleteArgs): Promise<PrismaItem> {
    return this.prisma.item.delete(args);
  }

  async findRentals(
    parentId: string,
    args: Prisma.RentalFindManyArgs
  ): Promise<PrismaRental[]> {
    return this.prisma.item
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .rentals(args);
  }

  async findReviews(
    parentId: string,
    args: Prisma.ReviewFindManyArgs
  ): Promise<PrismaReview[]> {
    return this.prisma.item
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .reviews(args);
  }

  async getLocation(parentId: string): Promise<PrismaLocation | null> {
    return this.prisma.item
      .findUnique({
        where: { id: parentId },
      })
      .location();
  }

  async getItemType(parentId: string): Promise<PrismaItemType | null> {
    return this.prisma.item
      .findUnique({
        where: { id: parentId },
      })
      .itemType();
  }
}
