/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { LocationWhereUniqueInput } from "../../location/base/LocationWhereUniqueInput";
import { RentalListRelationFilter } from "../../rental/base/RentalListRelationFilter";
import { ItemTypeWhereUniqueInput } from "../../itemType/base/ItemTypeWhereUniqueInput";
import { ReviewListRelationFilter } from "../../review/base/ReviewListRelationFilter";

@InputType()
class ItemWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  available?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => LocationWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => LocationWhereUniqueInput)
  @IsOptional()
  @Field(() => LocationWhereUniqueInput, {
    nullable: true,
  })
  location?: LocationWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => RentalListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RentalListRelationFilter)
  @IsOptional()
  @Field(() => RentalListRelationFilter, {
    nullable: true,
  })
  rentals?: RentalListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ItemTypeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ItemTypeWhereUniqueInput)
  @IsOptional()
  @Field(() => ItemTypeWhereUniqueInput, {
    nullable: true,
  })
  itemType?: ItemTypeWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ReviewListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ReviewListRelationFilter)
  @IsOptional()
  @Field(() => ReviewListRelationFilter, {
    nullable: true,
  })
  reviews?: ReviewListRelationFilter;
}

export { ItemWhereInput as ItemWhereInput };
